### ISSUE TITLE
regeneratorRuntime is not defined with gatsby v2

### ISSUE THREAD

**Issue by cedricdelpoux** [danoc/gatsby-source-strava-activities#2]
Hi, When I try to use your plugin, I get this error:

```
error Plugin gatsby-source-strava-activities returned an error
  ReferenceError: regeneratorRuntime is not defined
```

I tried to include `import '@babel/polyfill'` at the top of my `gatsby-browser.js` and to modify my `gatsby-node.js` with:

```
exports.onCreateBabelConfig = ({ babelrc }) => ({
  ...babelrc,
  plugins: babelrc.plugins.concat(['@babel/plugin-transform-regenerator']),
})
```

But it does not work

**Comment by danoc** [comment]
Hi @xuopled — I believe this has been fixed in the latest version. Thanks for the report!
